# Generated by Django 3.0.3 on 2020-02-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190317_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default='2020-02-28 07:03:20.254557', verbose_name='Herhangi bir tarih'),
            preserve_default=False,
        ),
    ]
