# Generated by Django 3.0.4 on 2024-03-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ogretmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tckimlik', models.CharField(max_length=11, verbose_name='TcKimlik')),
            ],
        ),
    ]
