# Generated by Django 4.1.4 on 2023-01-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_post_modified_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post/"),
        ),
    ]
