# Generated by Django 3.0.5 on 2020-04-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hesapKodu', models.CharField(max_length=20)),
                ('unvan', models.CharField(max_length=80)),
                ('ad', models.CharField(blank=True, max_length=40, null=True)),
                ('soyad', models.CharField(blank=True, max_length=40, null=True)),
                ('aktifPasif', models.IntegerField(blank=True, choices=[(0, 'Aktif'), (1, 'Pasif')], null=True)),
                ('field1', models.IntegerField(blank=True, null=True)),
                ('field2', models.IntegerField(blank=True, null=True)),
                ('field3', models.CharField(blank=True, max_length=20, null=True)),
                ('field4', models.CharField(blank=True, max_length=20, null=True)),
                ('field5', models.CharField(blank=True, max_length=20, null=True)),
                ('field6', models.CharField(blank=True, max_length=20, null=True)),
                ('field7', models.CharField(blank=True, max_length=20, null=True)),
                ('field8', models.CharField(blank=True, max_length=20, null=True)),
                ('resim', models.ImageField(blank=True, default='Static/pics/cari_pic/none/no-img.jpg', null=True, upload_to='Static/pics/cari_pic')),
                ('field10', models.CharField(blank=True, max_length=20, null=True)),
                ('field11', models.CharField(blank=True, max_length=20, null=True)),
                ('field12', models.CharField(blank=True, max_length=20, null=True)),
                ('field13', models.IntegerField(blank=True, null=True)),
                ('field14', models.IntegerField(blank=True, null=True)),
                ('field15', models.CharField(blank=True, max_length=20, null=True)),
                ('field16', models.BooleanField(blank=True, null=True)),
                ('field17', models.BooleanField(blank=True, null=True)),
                ('field18', models.CharField(blank=True, max_length=20, null=True)),
                ('field19', models.BooleanField(blank=True, null=True)),
                ('field20', models.EmailField(blank=True, max_length=50, null=True)),
                ('field21', models.CharField(blank=True, max_length=50, null=True)),
                ('field22', models.EmailField(blank=True, max_length=50, null=True)),
                ('field23', models.EmailField(blank=True, max_length=50, null=True)),
                ('field24', models.EmailField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
