# Generated by Django 3.0.5 on 2020-04-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200413_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='field16',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='field17',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='field19',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
