# Generated by Django 3.1.1 on 2020-11-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200418_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='field1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field10',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field11',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field12',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field13',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field14',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field15',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field16',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field17',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field18',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field19',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field20',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field21',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field22',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field23',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field24',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field3',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field4',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field5',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field6',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field7',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='field8',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='resim',
        ),
    ]
